### PR TITLE
Laravel 7.* & minor fix

### PR DESCRIPTION
**Pull request by JohnRoux**
* Updated guzzle and illuminate requirements

* Fixed `message->content` => `message->getContent()` since message content is now private

* Fixed messages not being wrapped in an array

### CODE REVIEW

**Review by neolikotsi — CHANGES_REQUESTED** [review]
Thanks John for the spot and fix. Can you change the array keys and keep the lower case then I will merge the pr.

**Comment by JohnRoux** [comment]
The docs specifically request it with that case, it works regardless of case, but I think it's better to follow the same request style as their docs?

**Comment by JohnRoux** [comment]
https://docs.smsportal.com/docs/rest-sending

**Comment by neolikotsi** [comment]
You are correct, the json api is not case sensitive. I try to resemble Laravel coding format. See code examples 
https://docs.smsportal.com/docs/rest-examples

**Comment by JohnRoux** [comment]
Cool cool, no stress. I'll update it when next online and push the case change 👍

**Pull request merged**
